### ISSUE TITLE
Configuration Problem 

### ISSUE THREAD

**Issue by Reena24** [royshil/SfM-Toy-Library#14]
I am trying to configure the Sfm - Toy - Library code but i get the error

Configuring done
WARNING: Target "SfMToyUI" requests linking to directory "E:/OpenCV/dep/libQGLViewer-2.5.1/QGLViewer/debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SfMToyUI" requests linking to directory "E:/OpenCV/dep/libQGLViewer-2.5.1/QGLViewer/debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SfMToyUI" requests linking to directory "E:/OpenCV/dep/libQGLViewer-2.5.1/QGLViewer/debug".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SfMToyUI" requests linking to directory "E:/OpenCV/dep/libQGLViewer-2.5.1/QGLViewer/debug".  Targets may link only to libraries.  CMake is dropping the item.
Generating done
So i added the path of the libraries 

but i still get the error 

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>Build started 3/8/2014 7:15:49 PM.
1>InitializeBuildStatus:
1>  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" because "AlwaysCreate" was specified.
1>FinalizeBuildStatus:
1>  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
1>  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.10
2>------ Build started: Project: SfMToyLibrary, Configuration: Debug Win32 ------
2>Build started 3/8/2014 7:15:49 PM.
2>InitializeBuildStatus:
2>  Touching "SfMToyLibrary.dir\Debug\SfMToyLibrary.unsuccessfulbuild".
2>CustomBuild:
2>  All outputs are up-to-date.
2>cl : Command line error D8021: invalid numeric argument '/Wno-sign-compare'
2>
2>Build FAILED.
2>
2>Time Elapsed 00:00:00.10
3>------ Build started: Project: SfMToyUI, Configuration: Debug Win32 ------
3>Build started 3/8/2014 7:15:49 PM.
3>InitializeBuildStatus:
3>  Touching "SfMToyUI.dir\Debug\SfMToyUI.unsuccessfulbuild".
3>CustomBuild:
3>  All outputs are up-to-date.
3>ClCompile:
3>  All outputs are up-to-date.
3>ManifestResourceCompile:
3>  All outputs are up-to-date.
3>LINK : fatal error LNK1104: cannot open file 'SfMToyLib\Debug\SfMToyLibrary.lib'
3>
3>Build FAILED.
3>
3>Time Elapsed 00:00:00.15
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug Win32 ------
4>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========

i have install libqglviewer in E:\OpenCV\dep\libQGLViewer-2.5.1
for 
QGLViewer_DIR_HINT  : E:/OpenCV/dep/libQGLViewer-2.5.1
QGLVIEWER_INCLUDE :E:/OpenCV/dep/libQGLViewer-2.5.1\QGLViewer
QGLVIEWER_LIB : E:\OpenCV\dep\libQGLViewer-2.5.1\QGLViewer\release

Can I know how to solve this problem please I am stuck with it for 1 week now. I would also like to know why the legacy folder is created because it was never include in the cmake configuration nor used .I would really like some help and explanation and how to go about compiling

**Comment by zhuzhu129130** [comment]
Error in `./SfMToyUI': realloc(): invalid pointer: 0x00007f33c7355840 ***
why?
ubuntu14.04

**Comment by royshil** [comment]
@zhuzhu129130 you should open a new issue ticket
and attach more information so I can figure out the problem.
this error message really doesn't have anything to go with
