### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by zshn25** [royshil/SfM-Toy-Library#26]
I've got 2 errors and 3 warnings
```
Error   1   error D8021: invalid numeric argument '/Wno-sign-compare'   C:\opencv_code\SfM-Toy-Library\SfMToyLib\cl SfMToyLibrary
Error   5   error LNK1104: cannot open file 'SfMToyLib\Debug\SfMToyLibrary.lib' C:\opencv_code\SfM-Toy-Library\LINK SfMToyUI
Warning 2   warning C4316: 'SFMViewer' : object allocated on the heap may not be aligned 16 C:\opencv_code\SfM-Toy-Library\ui_sfmtoy.h  63  1   SfMToyUI
Warning 4   warning C4316: 'SFMViewer' : object allocated on the heap may not be aligned 16 C:\opencv_code\SfM-Toy-Library\ui_sfmtoy.h  63  1   SfMToyUI
Warning 3   warning C4172: returning address of local variable or temporary C:\opencv_code\SfM-Toy-Library\source\SfMToyLib\Distance.h  70  1   SfMToyUI
```
After a lot of time tweaking, I managed to remove ```/Wno-sign-compare``` 
![image](https://cloud.githubusercontent.com/assets/5270999/13626791/317dec4c-e5eb-11e5-98de-ea5651482c1e.png)

and then I added these lines in the top of common.h
```
#ifdef WIN32
#define WIN32_LEAN_AND_MEAN 1
#define NOMINMAX 1
#include <Windows.h>
#endif
```
 build it successfully. Now when I try to run it, it asked for many ```dll``` files which I included in the executable folder.
![image](https://cloud.githubusercontent.com/assets/5270999/12675076/c9a7bef6-c6ad-11e5-98e2-4a2d306fdea8.png)
![image](https://cloud.githubusercontent.com/assets/5270999/12675101/ee02cebc-c6ad-11e5-9011-36983182d339.png)
At last, when I added all these dlls, it gave me this error
![image](https://cloud.githubusercontent.com/assets/5270999/12675124/169a3da6-c6ae-11e5-87b6-8738ae5b173d.png)

**Comment by royshil** [comment]
@zshn25  Please try to build and run it now, I've moved the core to Qt5
Also try the latest libQGLViewer version

**Comment by zshn25** [comment]
Thanks a lot @royshil. I ran the updated version. Still showed me all errors as before except the last one. This time it runs but doesn't show any output.
![image](https://cloud.githubusercontent.com/assets/5270999/12711082/d9358196-c8e2-11e5-8161-fae06af633ad.png)

```
Assertion failed: (reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****", file c:\eigen-eigen-b30b87236a1b\source\eigen\src/Core/DenseStorage.h, line 86
```

**Comment by royshil** [comment]
@zshn25 Please run in debug to see what is the offending line that it crashed on

**Comment by zshn25** [comment]
Can't run it in Debug mode. It throws me this error
![image](https://cloud.githubusercontent.com/assets/5270999/13565831/849c69c2-e478-11e5-89e8-8c7b0242f345.png)

**Comment by tmac1002** [comment]
I also had the same error information with you for a long time. I really hope @royshil can help us to tackle it.

**Comment by royshil** [comment]
I'm not very familiar with recent versions of Visual Studio.
But, in CMake you should be able to setup the build type to be debug: CMAKE_BUILD_TYPE
Try setting it to 'Debug' and see if that allows you to debug.

**Comment by tmac1002** [comment]
I always meet the error on the function of update(). Could you please tell me what's the practical function about this function. If it is only as a visualization. I was wondering that if I could skip that update() function and continue run because I only just want to get the 3D point. Thank you very much. @royshil

**Comment by royshil** [comment]
@tmac1002 indeed it's only for visualization, so you can comment it out.
